nama = input("Nama: ")
nim = input("NIM: ")
kelas_paralel = input("Kelas Paralel: ")
ttl = input("Tempat/Tanggal Lahir: ")
alamat = input("Alamat: ")
hobby = input("Hobby: ")
no_hp = input("No. Hp: ")
print("          ")
print(f"Nama: {nama}")
print(f"NIM: {nim}")
print(f"Kelas Paralel: {kelas_paralel}")
print(f"Tempat/Tanggal Lahir: {ttl}")
print(f"Alamat: {alamat}")
print(f"Hobby: {hobby}")
print(f"No. HP: {no_hp}")