print ("##############################")
print ("#                            #")
print ("#    Amandha Citra Mustika   #")
print ("#        2410817320004       #")
print ("#                            #")
print ("##############################")